### ISSUE TITLE
where to download the file "db_celldepot.sql"

### ISSUE THREAD

**Issue by s1sun** [interactivereport/CellDepot#1]
There is a sql file mentioned from install_manual. And it can be downloaded from https://celldepot.bxgenomics.com/celldepot_manual/db_celldepot.sql.
However, I did not find it. Could you please point me how to find it? Thanks

**Comment by dercyc** [comment]
Hi there, would you like to try again? Thanks.

--Derrick

**Comment by s1sun** [comment]
It is working now. Nice. Thanks so much.
