### ISSUE TITLE
Import/Create Project options does not seem to work

### ISSUE THREAD

**Issue by Sachinyadav55** [interactivereport/CellDepot#3]
Hi, I am trying to deploy this app locally on centOS , following the isntructions specified at
https://celldepot.bxgenomics.com/celldepot_manual/install_environment.php 
and https://bioinforx.com/lims2/help_requirement.php

The set up was completed successfully and I was able to see the CellDepot interface on port 80 - I faced two issues 

1) The override settings do not seem to work - the app still seem to take the default username and password for log in

2) The import project and create project functions don't seem to accept an entry. I have my h5ad files in the location specified and running cellxgene I am able to access them as well. But when i try to import data into celldepot using the example teplate.csv I get 'The system did not import any data' error. 

I was able to verify that the mariadb user credentials work and is able to write to the App_Project table. But the app is not able to import into the database tables. 

Could you please suggest how to check if the app can connect to MariaDB using the credentials configured or if there is any issues with inserting the data?

**Comment by Sachinyadav55** [comment]
Some of the files controlling admin login like user_admin.php were missing from this repo. and files in EFS drive were not readble by the app even with 777 permissions. Moving the input files to local drive fixed the issue

**Comment by pkhoueiry** [comment]
@Sachinyadav55 and @baohongz where did you get the user_admin.php from? My instance of celldepot has the same behavior for guest and admin users! For instnace, guest user can upload projects which is not supposed to be the case. Also, when comparing the interface to the tutorial one, the admin user in my case does not have the tab "Admin tools".

**Comment by dercyc** [comment]
We had a meeting with Sachin to troubleshooting the issue. It was caused by the IT setup:
- The data folder was in the network drive and the Apache user didn't have permission to access. Solved by moving the data directory to the local drive.
- The Apache user did not have access to Redis. Solved by turning off the SE Linux
- The Apache user did not have write access to SQLite. Solved by turning off the SE Linux.

**Comment by dercyc** [comment]
> @Sachinyadav55 and @baohongz where did you get the user_admin.php from? My instance of celldepot has the same behavior for guest and admin users! For instnace, guest user can upload projects which is not supposed to be the case. Also, when comparing the interface to the tutorial one, the admin user in my case does not have the tab "Admin tools".

1.) The user_admin.php was originally for internal use. We decide to open source it. It is now available in the repository.
2.) Make sure that you have the following settings in your override_settings.php:
$BXAF_CONFIG_CUSTOM['GUEST_ACCOUNT']					= 'guest@bioinforx.com';
$BXAF_CONFIG_CUSTOM['GUEST_ACCOUNT_AUTO']				= true;

This will tell the CellDepot if it is a guest account.

3.) The admin tools only shows up if you log in as admin user, i.e., admin@bioinforx.com, or other accounts defined in
$BXAF_CONFIG_CUSTOM['Admin_User_Email']					= array('admin@bioinforx.com');

**Comment by pkhoueiry** [comment]
Thanks for the prompt reply and for sharing the admin tool. It works now.
I still have two minor issues:
1) "Sign in as guest" is still prompting the message "The guest account is not available." although I set to true the  "$BXAF_CONFIG_CUSTOM['GUEST_ACCOUNT_AUTO'] = true". The GUEST_ACCOUNT has the same email as in the users.db database.
2) When logged in as guest (using the guest email and password defined in users.db), we can still import project. In the manual it is said that only admin is allowed to import projects.
